# Generated by Django 4.1.7 on 2023-03-12 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vorname', models.CharField(max_length=100)),
                ('telefonnummer', models.CharField(max_length=100)),
                ('projekt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Eintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('doku', models.TextField(max_length=1000)),
                ('bild', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokusys.klient')),
            ],
        ),
    ]
