# Generated by Django 4.1.7 on 2023-03-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokusys', '0002_alter_eintrag_datum'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='bemerkung',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
